maintainer       "Adam Ward"
maintainer_email "adamw@subdesigns.net"
license          "MIT"
name             "remote_file_s3"
description      "Pure Ruby Chef LWRP for pulling files from S3"
long_description "Pure Ruby Chef LWRP for pulling files from S3"
version          "1.0.0"
